
import java.io.File;
import java.util.regex.Pattern;
import javax.swing.DefaultListModel;


public class ClientApp extends javax.swing.JFrame
{
    Utils u;
    Server srv;
    String path;
    String pathMover;
    DefaultListModel<String> listModel;
    
    public ClientApp() {
        this.setTitle("Sistema de Ficheiros");
        initComponents();
    }
    
    public ClientApp(Utils u){
        this.u = u;
        this.setTitle("Sistema de Ficheiros");
        initComponents();
    }
    
    public ClientApp(Server srv) {
        this.srv = srv;
        this.setTitle("Sistema de Ficheiros");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList = new javax.swing.JList();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        loginMenuItem = new javax.swing.JMenuItem();
        logoutMenuItem = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jChat = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMoverPara = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jCopiarPara = new javax.swing.JMenuItem();
        deleteMenuItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        aboutMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jList.setEnabled(false);
        jScrollPane1.setViewportView(jList);

        jButton1.setText("->");
        jButton1.setEnabled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("<-");
        jButton2.setEnabled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        fileMenu.setMnemonic('f');
        fileMenu.setText("Ficheiro");

        loginMenuItem.setMnemonic('o');
        loginMenuItem.setText("Login");
        loginMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(loginMenuItem);

        logoutMenuItem.setMnemonic('s');
        logoutMenuItem.setText("Logout");
        logoutMenuItem.setEnabled(false);
        logoutMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(logoutMenuItem);

        jMenuItem1.setText("Registar");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        fileMenu.add(jMenuItem1);

        jChat.setText("Chat");
        jChat.setEnabled(false);
        jChat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChatActionPerformed(evt);
            }
        });
        fileMenu.add(jChat);

        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Sair");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        editMenu.setMnemonic('e');
        editMenu.setText("Editar");

        jMenuItem2.setText("Criar ficheiro");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        editMenu.add(jMenuItem2);

        jMenuItem3.setText("Criar directoria");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        editMenu.add(jMenuItem3);

        jMenuItem4.setText("Mover de");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        editMenu.add(jMenuItem4);

        jMoverPara.setText("Mover para");
        jMoverPara.setEnabled(false);
        jMoverPara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMoverParaActionPerformed(evt);
            }
        });
        editMenu.add(jMoverPara);

        jMenuItem5.setText("Copiar de");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        editMenu.add(jMenuItem5);

        jCopiarPara.setText("Copiar para");
        jCopiarPara.setEnabled(false);
        jCopiarPara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCopiarParaActionPerformed(evt);
            }
        });
        editMenu.add(jCopiarPara);

        deleteMenuItem.setMnemonic('d');
        deleteMenuItem.setText("Apagar");
        deleteMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteMenuItemActionPerformed(evt);
            }
        });
        editMenu.add(deleteMenuItem);

        menuBar.add(editMenu);

        helpMenu.setMnemonic('h');
        helpMenu.setText("Ajuda");

        aboutMenuItem.setMnemonic('a');
        aboutMenuItem.setText("Acerca");
        aboutMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutMenuItemActionPerformed(evt);
            }
        });
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 612, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    // Sair
    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    // Login
    private void loginMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginMenuItemActionPerformed
        LoginScreen l = new LoginScreen(this, rootPaneCheckingEnabled, srv);
        this.u = l.showDialog();
        
        if (u != null) {
            loginMenuItem.setEnabled(false);
            logoutMenuItem.setEnabled(true);
            jList.setEnabled(true);
            jButton1.setEnabled(true);
            jButton2.setEnabled(true);
            jChat.setEnabled(true);
        }
    }//GEN-LAST:event_loginMenuItemActionPerformed
    
    
    private void aboutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutMenuItemActionPerformed
        About a = new About(this, rootPaneCheckingEnabled);
        a.setVisible(true);
    }//GEN-LAST:event_aboutMenuItemActionPerformed

    // Logout
    private void logoutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutMenuItemActionPerformed
        if (u.logout()) {
            logoutMenuItem.setEnabled(false);
            loginMenuItem.setEnabled(true);
        }
    }//GEN-LAST:event_logoutMenuItemActionPerformed

    // Registar
    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        RegistarScreen r = new RegistarScreen(this, rootPaneCheckingEnabled, srv);
        this.u = r.showDialog();
        
        if (u != null) {
            loginMenuItem.setEnabled(false);
            logoutMenuItem.setEnabled(true);
            jList.setEnabled(true);
            jButton1.setEnabled(true);
            jButton2.setEnabled(true);
            jChat.setEnabled(true);
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    // Criar ficheiro
    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        CreateFile cf = new CreateFile(this, rootPaneCheckingEnabled, u, true);
        cf.showDialog(path);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    // Criar directoria
    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        CreateFile cf = new CreateFile(this, rootPaneCheckingEnabled, u, false);
        cf.showDialog(path);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    // Dir seguinte
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
   
        String obj = null;
        DirectoryInfo dinfo = null;
        listModel = new DefaultListModel<>();
        
        if (path == null)
            path = File.separator;
        
        if (jList.getSelectedIndex() != -1) {
            obj = (String) jList.getSelectedValue();
        
            String[] arr = obj.split(":");
            if (arr[0].equals("dir")) {
                path = path+File.separator+arr[arr.length-1];
            }
            else if (arr[0].equals("file")) {
                // DOWNLOAD
                if (u.getFileContent(path+File.separator+arr[arr.length-1]))
                    System.out.println("FICHEIRO TRANSFERIDO");
            }
        }
        
        dinfo = u.changeWorkingDirectory(path);

        if (dinfo != null) {
            for (String str : dinfo.getDir()) {
                listModel.addElement("dir:"+str);
            }
            
            for (String str2 : dinfo.getFicheirosName()) {
                listModel.addElement("file:"+str2);
            }
        }
        
        jList.setModel(listModel);
    }//GEN-LAST:event_jButton1ActionPerformed

    // CHAT
    private void jChatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChatActionPerformed
        Chat c = new Chat(u.getUsername(), srv.getServerName(), "127.0.0.1", 1338);
        c.setVisible(true);
        jChat.setEnabled(false);
    }//GEN-LAST:event_jChatActionPerformed

    // Dir anterior
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        DirectoryInfo dinfo = null;
        listModel = new DefaultListModel<>();
        
        if (path == null)
            path = File.separator;
        
        String pattern = Pattern.quote(System.getProperty("file.separator"));
        String[] arr = path.split(pattern);
        
        path = File.separator;
        for (int i = 0; i < arr.length-1; i++) {
            path = arr[i]+File.separator;
        }
        
        dinfo = u.changeWorkingDirectory(path);

        if (dinfo != null) {
            for (String str : dinfo.getDir()) {
                listModel.addElement("dir:"+str);
            }
            
            for (String str2 : dinfo.getFicheirosName()) {
                listModel.addElement("file:"+str2);
            }
        }
        
        jList.setModel(listModel);
    }//GEN-LAST:event_jButton2ActionPerformed

    // MOVER DE
    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        
        String obj = null;
        listModel = new DefaultListModel<>();
        
        if (path == null)
            path = File.separator;
        
        if (jList.getSelectedIndex() != -1) {
            obj = (String) jList.getSelectedValue();
        
            String[] arr = obj.split(":");
            if (arr[0].equals("file")) {
                pathMover = path+File.separator+arr[arr.length-1];
            }
        }
        
        jMoverPara.setEnabled(true);
        
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    // MOVER PARA
    private void jMoverParaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMoverParaActionPerformed
        
        u.moveFile(pathMover, path);
        jMoverPara.setEnabled(false);
        
    }//GEN-LAST:event_jMoverParaActionPerformed

    // APAGAR FICHEIRO
    private void deleteMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteMenuItemActionPerformed
        
        String obj = null;
        listModel = new DefaultListModel<>();
        
        if (path == null)
            path = File.separator;
        
        if (jList.getSelectedIndex() != -1) {
            obj = (String) jList.getSelectedValue();
        
            String[] arr = obj.split(":");
            if (arr[0].equals("file"))
                if(u.removeFile(path+File.separator+arr[arr.length-1]))
                    System.out.println("Apagou ficheiro!");
        }
        
    }//GEN-LAST:event_deleteMenuItemActionPerformed

    // COPIAR DE
    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        
        String obj = null;
        listModel = new DefaultListModel<>();
        
        if (path == null)
            path = File.separator;
        
        if (jList.getSelectedIndex() != -1) {
            obj = (String) jList.getSelectedValue();
        
            String[] arr = obj.split(":");
            if (arr[0].equals("file")) {
                pathMover = path+File.separator+arr[arr.length-1];
            }
        }
        
        jCopiarPara.setEnabled(true);
        
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    // COPIAR PARA
    private void jCopiarParaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCopiarParaActionPerformed
        
        u.copyFile(pathMover, path);
        jCopiarPara.setEnabled(false);
        
    }//GEN-LAST:event_jCopiarParaActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClientApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClientApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClientApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClientApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClientApp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JMenuItem deleteMenuItem;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JMenuItem jChat;
    private javax.swing.JMenuItem jCopiarPara;
    private javax.swing.JList jList;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMoverPara;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem loginMenuItem;
    private javax.swing.JMenuItem logoutMenuItem;
    private javax.swing.JMenuBar menuBar;
    // End of variables declaration//GEN-END:variables

}
