import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.net.DatagramPacket;
import java.net.DatagramSocket;
import java.net.InetAddress;
import java.net.SocketException;
import java.net.SocketTimeoutException;
import java.net.UnknownHostException;
import java.util.List;
import javax.swing.DefaultListModel;

public class ServerList extends javax.swing.JFrame 
{
    InfoParaCliente info = null;
    DatagramSocket s;
    DatagramPacket p;
    ByteArrayInputStream bin;
    ByteArrayOutputStream bout;
    ObjectInputStream in;
    ObjectOutputStream out;
    Object servInfo = null;
    String ipServDir = "127.0.0.1";
    int portoServDir = 1338;
    DefaultListModel<String> listModel;
    
    /**
     * Creates new form ServerList
     */
    public ServerList() {
        initComponents();
        
        listModel = new DefaultListModel<>();
        
        try {
            // Enviar pacote UDP para o Serviço de Directoria
            s = new DatagramSocket();
            s.setSoTimeout(30000);
        
            bout = new ByteArrayOutputStream();
            out = new ObjectOutputStream(bout);
            out.writeObject("<QUERO_LISTA>");
            out.flush();
            
            p = new DatagramPacket(bout.toByteArray(), bout.size(), InetAddress.getByName(ipServDir), portoServDir);
            s.send(p);
        
            // Recebe objecto
            p = new DatagramPacket(new byte[4096], 4096);
            s.receive(p);
            
            in = new ObjectInputStream(new ByteArrayInputStream(p.getData(), 0, p.getLength()));
            servInfo = in.readObject();
            
            if (servInfo instanceof InfoParaCliente)
            {
                info = (InfoParaCliente) servInfo;

                System.out.println("Recebi InfoParaCliente:" + info.getListaServers().size());
                System.out.println("Recebi InfoParaCliente:" + info.getListaServers().get(0).getPortTCP());

                if (info.getListaServers().isEmpty())
                    jBtnLigar.setEnabled(false);
                else
                    jBtnLigar.setEnabled(true);
                
                for (Server s : info.getListaServers()) {
                    listModel.addElement(s.getServerName());
                }
                
                jServList.setModel(listModel);
            }
            else
                jBtnLigar.setEnabled(false);
            
            System.out.println("Cheguei AQUI !");     
        } catch(UnknownHostException e) {
            System.out.println("Erro " + e);
        } catch(SocketTimeoutException e) {
            System.out.println("Erro " + e);
        } catch(SocketException e) {
            System.out.println("Erro " + e);
        } catch(IOException e) {
            System.out.println("Erro " + e);
        } catch (ClassNotFoundException e) {
            System.out.println("Erro " + e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jServList = new javax.swing.JList();
        jButton1 = new javax.swing.JButton();
        jBtnLigar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Servidores");

        jScrollPane1.setViewportView(jServList);

        jButton1.setText("Cancelar");

        jBtnLigar.setText("Ligar");
        jBtnLigar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnLigarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBtnLigar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jBtnLigar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnLigarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnLigarActionPerformed
        // Ligar a um Servidor!
        int index = jServList.getSelectedIndex();
        
        new ClientApp(info.getListaServers().get(index)).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jBtnLigarActionPerformed


    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ServerList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ServerList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ServerList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ServerList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ServerList().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnLigar;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList jServList;
    // End of variables declaration//GEN-END:variables
}
